# Any human PLAYER
archetype "human-player" (cap 256) (per obs) (raycast-visible) (player) (non-occluder) (occupies-env-grid) (infer-kind-override human player)
{
    # Placement participation (plan section 18): which spatial relations this
    # archetype takes part in - the write seams validate both ends.
    (spatial grip)
    (attr "physical-motors")
    (attr "game-role")
    # Lifecycle dates - written by historical sim, surface into interactive.
    (attr "birth-date")
    (attr "death-date")
    (attr "death-cause")
    (attr "age-group")
    (attr "gender")
    (attr "appearance")
    (attr "height")
    (attr "girth")
    (attr "hair-color")
    (attr "eye-color")
    (attr "attractiveness")
    (attr "name")
    (attr "condition")
    (attr "pregnant-when")
    (attr "fatigue")
    (attr "hunger")
    (attr "adrenaline")
    (attr "sleepiness")
    (attr "appetite")
    (attr "sexual-orient")
    # Big Five personality - the ten Big Five Aspect Scale aspects.
    (attr "openness")
    (attr "intellect")
    (attr "industriousness")
    (attr "orderliness")
    (attr "enthusiasm")
    (attr "assertiveness")
    (attr "compassion")
    (attr "politeness")
    (attr "volatility")
    (attr "withdrawal")
    # Dark-tetrad traits - genetic, drive crime motives.
    (attr "narcissism")
    (attr "machiavellianism")
    (attr "psychopathy")
    (attr "sadism")
    # Physical traits (PR-3b 2026-05-25) - genetic, drive method viability.
    (attr "strength")
    (attr "dexterity")
    (attr "agility")
    (attr "endurance")
    (attr "region")
    # The body plan (plan section 18) - same slots as human-npc.
    (struct child "left-hand" [k left-hand] (offset 0 -0.04 0))
    (struct child "right-hand" [k right-hand] (offset 0 0.04 0))
    (struct child "head" [k head] (offset 0 1.6 0))
    (struct child "eyes" [k eye] (offset 0 1.6 0))
    (struct child "mouth" [k mouth] (offset 0 1.55 0.03))
    (struct child "torso" [k torso] (offset 0 1.2 0))
    (attr "pregnant-by")
    (spatial bounds)
}
