# Any human PLAYER
archetype "human_player" [256] /obs /raycast_visible /player /non_occluder /occupies_env_grid /infer_kind_override human player
{
    "physical_motors"
    "role"
    # Lifecycle dates - written by historical sim, surface into interactive.
    "birth_date"
    "death_date"
    "death_cause"
    "age_group"
    "gender"
    "appearance"
    "height"
    "girth"
    "name"
    "condition"
    "pregnant_when"
    "alertness"
    "sexual_orient"
    "interests"
    # Big Five personality - the ten Big Five Aspect Scale aspects.
    "openness"
    "intellect"
    "industriousness"
    "orderliness"
    "enthusiasm"
    "assertiveness"
    "compassion"
    "politeness"
    "volatility"
    "withdrawal"
    # Dark-tetrad traits - genetic, drive crime motives.
    "narcissism"
    "machiavellianism"
    "psychopathy"
    "sadism"
    "region"
    # Parts are not auto-perceived — we perceive specific body-parts below instead
    "parts"
    "left_hand"
    "right_hand"
    "head"
    "eyes"
    "mouth"
    "pregnant_by"
    "control"
    "obb"
}
