# Any human NPC
archetype "human_npc" [256] /obs /raycast_visible /sentient /non_occluder /occupies_env_grid /infer_kind_override human nonplayer
{
    "visual_sensor"
    "sound_sensor"
    "physical_motors"
    "role"
    "perform"
    "date"
    "age"
    "age_group"
    "gender"
    "appearance"
    "height"
    "girth"
    # NPCs learn their own name through self-awareness, not passive perception
    "name"
    "nationality"
    "condition"
    "pregnant_when"
    "alertness"
    "sexual_orient"
    "charisma"
    "romanticism"
    "passion"
    "extroversion"
    "intelligence"
    "interests"
    "in"
    "region"
    # Parts are not auto-perceived — we perceive specific body-parts below instead
    "parts"
    "left_hand"
    "right_hand"
    "eyes"
    "mouth"
    "conversation"
    "pregnant_by"
    "control"
    "obb"
}
