# Any human PLAYER
archetype "human_player" [256] /obs /raycastVisible /player /nonOccluder /inferKindOverride human player
{
    "physical-motors"
    "role"
    "date"
    "age"
    "ageGroup"
    "gender"
    "appearance"
    "height"
    "girth"
    "name"
    "nationality"
    "condition"
    "pregnantWhen"
    "alertness"
    "in"
    "region"
    # Parts are not auto-perceived — we perceive specific body-parts below instead
    "parts"
    "leftHand"
    "rightHand"
    "eyes"
    "mouth"
    "conversation"
    "pregnantBy"
    "control"
    "obb"
}
