# Any human NPC
archetype "human_npc" [256] /obs /raycastVisible /sentient /nonOccluder /inferKindOverride human nonplayer
{
    "visual-sensor"
    "sound-sensor"
    "physical-motors"
    "role"
    "perform"
    "date"
    "age"
    "ageGroup"
    "gender"
    "appearance"
    "height"
    "girth"
    # NPCs learn their own name through self-awareness, not passive perception
    "name"
    "nationality"
    "condition"
    "pregnantWhen"
    "alertness"
    "sexualOrient"
    "charisma"
    "romanticism"
    "passion"
    "extroversion"
    "intelligence"
    "interests"
    "in"
    "region"
    # Parts are not auto-perceived — we perceive specific body-parts below instead
    "parts"
    "leftHand"
    "rightHand"
    "eyes"
    "mouth"
    "conversation"
    "pregnantBy"
    "control"
    "obb"
}
